<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="LabApi">
      <HintPath>Libs\LabApi.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="CommandSystem.Core">
      <HintPath>Libs\CommandSystem.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Mirror">
      <HintPath>Libs\Mirror.dll</HintPath>
      <Private>false</Private>
    </Reference>

    <Reference Include="Assembly-CSharp">
      <HintPath>Libs\Assembly-CSharp.dll</HintPath>
    </Reference>

    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>Libs\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>

    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
